### ISSUE TITLE
Version discrepancy with sprintf-js / [sprintf] unexpected placeholder

### ISSUE THREAD

**Issue by Suisse00** [ryym/mocha-each#11]
I don't know how this issue will end (with a PR or just as a "For Your Information") but :

The reason for the error: You are using a feature of sprintf-js in the future!
Just do a `npm install sprintf-js` to get the latest v1 version instead of relying on the one set in the dependency of mocha-each.

The source of the issue (for the PR): mocha-each configured the version of sprintf-js with the prefix "^" in 1.0.3. That means if the version contains à .0. somewhere (like here) it will be more restrictive on the version and will NOT allow .0. to become .1.

So the npm dependencies engine will only download version 1.0.*.
Meanwhile, they added some new features (new types, named arguments & lazy value).

**Comment by ryym** [comment]
You mean you want to use `sprintf-js` version `1.1` or later, right?
It should be possible without updating `mocha-each`'s package.json. See the npm document.

<https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept>

If you specify the dependency version using the `^` prefix, it allows any minor version updates as well as the patch version updates. For example, `^1.0.4` allows:

- `1.0.4`, `1.0.5`, `1.0.6`, ...and so on
- `1.1.0`, `1.1.1`, `1.1.2`, ..., `1.2.0`, `1.2.1`, ..., `1.3.0`, ...and so on

and it does not allows:

- the versions smaller than `1.0.4`
- the versions bigger than or equal to `2.0.0`

I confirmed that by creating a sample repository with the package.json:

```json
{
  "name": "tmp",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "mocha-each": "^2.0.1"
  }
}
```

It downloads `sprintf-js` v1.1.2, the latest version.

```bash
$ npm ls
tmp@1.0.0 /Users/ryu/work/tmp
└─┬ mocha-each@2.0.1
  └── sprintf-js@1.1.2
```

FYI, you can inspect the version syntax at <https://semver.npmjs.com/>.

**Comment by Suisse00** [comment]
So... let do if I didn't post anything!

BTW thanks for the semver.npmjs.com! I'm kinda sad they only put a link to semver.npmjs.com in the about page of semver and not https://docs.npmjs.com/misc/semver as well...
