### ISSUE TITLE
API: add support for parameterization at `describe` level

### ISSUE THREAD

**Issue by iacopy** [ryym/mocha-each#2]
Currently, the API supports only this pattern:

`forEach(parameters).it(title, testCase)`

In my opinion, It would be useful to support also:

`forEach(parameters).describe(title, contextCase)`

to pass same parameters to different test cases (this also allows a sort of parameters "product").

**Comment by ryym** [comment]
Thanks for the suggestion. It is an interesting idea,
but to be honest, I have not been actively maintaining this repository anymore,
so there are no plans to implement new features at the moment.
Pull Requests are welcome :)
