### ISSUE TITLE
SyntaxError on v2.0.0

### ISSUE THREAD

**Issue by waitsangbv** [ryym/mocha-each#9]
With v2.0.0, require('mocha-each') caused "SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0) while parsing /node_modules/mocha-each/build/index.js". 
It was working fine with v1.2.0

**Comment by ryym** [comment]
Thanks for reporting!
The build task failed silently. I'll fix it soon.

**Comment by ryym** [comment]
Fixed version v2.0.1 was released!
